CLASS zcl_lab_39_budget_ya DEFINITION ABSTRACT
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.

    METHODS  get_budget ABSTRACT RETURNING VALUE(rv_budget) TYPE string.
PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_39_budget_ya IMPLEMENTATION.
ENDCLASS.
