CLASS zcl_lab_29_organization_ya DEFINITION ABSTRACT
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS get_location  ABSTRACT RETURNING VALUE(rv_location) TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_29_organization_ya IMPLEMENTATION.
ENDCLASS.
